
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADD DIV LPAREN MULT NUMBER RPAREN SUBoperacao : calcoperacao : operacao ADD calcoperacao : operacao SUB calccalc : NUMBERcalc : calc MULT NUMBERcalc : calc DIV NUMBERexpressao : LPAREN operacao RPAREN '
    
_lr_action_items = {'NUMBER':([0,4,5,6,7,],[3,3,3,10,11,]),'$end':([1,2,3,8,9,10,11,],[0,-1,-4,-2,-3,-5,-6,]),'ADD':([1,2,3,8,9,10,11,],[4,-1,-4,-2,-3,-5,-6,]),'SUB':([1,2,3,8,9,10,11,],[5,-1,-4,-2,-3,-5,-6,]),'MULT':([2,3,8,9,10,11,],[6,-4,6,6,-5,-6,]),'DIV':([2,3,8,9,10,11,],[7,-4,7,7,-5,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'operacao':([0,],[1,]),'calc':([0,4,5,],[2,8,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> operacao","S'",1,None,None,None),
  ('operacao -> calc','operacao',1,'p_operacao_1','calc_yacc.py',6),
  ('operacao -> operacao ADD calc','operacao',3,'p_operacao_2','calc_yacc.py',10),
  ('operacao -> operacao SUB calc','operacao',3,'p_operacao_3','calc_yacc.py',14),
  ('calc -> NUMBER','calc',1,'p_cal_1','calc_yacc.py',18),
  ('calc -> calc MULT NUMBER','calc',3,'p_cal_2','calc_yacc.py',23),
  ('calc -> calc DIV NUMBER','calc',3,'p_cal_3','calc_yacc.py',27),
  ('expressao -> LPAREN operacao RPAREN','expressao',3,'p_expressao','calc_yacc.py',31),
]
