
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'rightNEGleftCONleftDISleftIMPleftEQUIVCON DIS EQUIV IMP LPAREN NEG PROP RPARENexpressao : NEG expressaoexpressao : expressao CON expressaoexpressao : expressao DIS expressaoexpressao : expressao IMP expressaoexpressao : expressao EQUIV expressaoexpressao : LPAREN expressao RPARENexpressao : PROP'
    
_lr_action_items = {'NEG':([0,2,3,5,6,7,8,],[2,2,2,2,2,2,2,]),'LPAREN':([0,2,3,5,6,7,8,],[3,3,3,3,3,3,3,]),'PROP':([0,2,3,5,6,7,8,],[4,4,4,4,4,4,4,]),'$end':([1,4,9,11,12,13,14,15,],[0,-7,-1,-2,-3,-4,-5,-6,]),'CON':([1,4,9,10,11,12,13,14,15,],[5,-7,5,5,-2,-3,-4,-5,-6,]),'DIS':([1,4,9,10,11,12,13,14,15,],[6,-7,6,6,6,-3,-4,-5,-6,]),'IMP':([1,4,9,10,11,12,13,14,15,],[7,-7,7,7,7,7,-4,-5,-6,]),'EQUIV':([1,4,9,10,11,12,13,14,15,],[8,-7,8,8,8,8,8,-5,-6,]),'RPAREN':([4,9,10,11,12,13,14,15,],[-7,-1,15,-2,-3,-4,-5,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expressao':([0,2,3,5,6,7,8,],[1,9,10,11,12,13,14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expressao","S'",1,None,None,None),
  ('expressao -> NEG expressao','expressao',2,'p_expressao_neg','yacc.py',15),
  ('expressao -> expressao CON expressao','expressao',3,'p_expressao_con','yacc.py',20),
  ('expressao -> expressao DIS expressao','expressao',3,'p_expressao_dis','yacc.py',25),
  ('expressao -> expressao IMP expressao','expressao',3,'p_expressao_imp','yacc.py',30),
  ('expressao -> expressao EQUIV expressao','expressao',3,'p_expressao_equiv','yacc.py',35),
  ('expressao -> LPAREN expressao RPAREN','expressao',3,'p_expressao_pars','yacc.py',40),
  ('expressao -> PROP','expressao',1,'p_expressao_PROP','yacc.py',45),
]
