
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DP INDICE NAME PG PRICE QP QUANTITY Typetudo : tudo encomenda\n| encomendaencomenda : Type DP lista_alimentoslista_alimentos : lista_alimentos alimento\n| alimentoalimento : INDICE QP NAME QP PRICE QP QUANTITY PG'
    
_lr_action_items = {'Type':([0,1,2,4,6,7,9,16,],[3,3,-2,-1,-3,-5,-4,-6,]),'$end':([1,2,4,6,7,9,16,],[0,-2,-1,-3,-5,-4,-6,]),'DP':([3,],[5,]),'INDICE':([5,6,7,9,16,],[8,8,-5,-4,-6,]),'QP':([8,11,13,],[10,12,14,]),'NAME':([10,],[11,]),'PRICE':([12,],[13,]),'QUANTITY':([14,],[15,]),'PG':([15,],[16,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'tudo':([0,],[1,]),'encomenda':([0,1,],[2,4,]),'lista_alimentos':([5,],[6,]),'alimento':([5,6,],[7,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> tudo","S'",1,None,None,None),
  ('tudo -> tudo encomenda','tudo',2,'p_tudo','yacc.py',6),
  ('tudo -> encomenda','tudo',1,'p_tudo','yacc.py',7),
  ('encomenda -> Type DP lista_alimentos','encomenda',3,'p_encomenda','yacc.py',12),
  ('lista_alimentos -> lista_alimentos alimento','lista_alimentos',2,'p_lista_alimentos','yacc.py',17),
  ('lista_alimentos -> alimento','lista_alimentos',1,'p_lista_alimentos','yacc.py',18),
  ('alimento -> INDICE QP NAME QP PRICE QP QUANTITY PG','alimento',8,'p_alimento','yacc.py',23),
]
